CREATE DATABASE IF NOT EXISTS EXPENSE_TRACKER;
USE EXPENSE_TRACKER;

#create category table and populate it
CREATE TABLE CATEGORIES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE
);
INSERT INTO CATEGORIES (NAME) VALUES 
('GROCERIES'), ('UTILITIES'), ('ENTERTAINMENT'), ('TAXES'), ('DEBT_PAYMENT'), 
('INSURANCE'), ('TRANSPORATION'), ('RENT'), ('HOUSING'), ('SAVINGS'),
('INVESTMENTS'), ('SUBSCRIPTIONS'), ('GIFTS'), ('PERSONAL_CARE'),
('MISCELLANEOUS'), ('DINING_OUT'), ('HEALTH_CARE'), ('PERSONAL_EXPENSES'), 
('EDUCATION'), ('PETS'), ('CHILD_CARE'), ('TRAVEL'), ('TECHNOLOGY'),
('LUXURY'), ('TAXES'), ('BUSINESS EXPENSES'), ('EVENTS'), ('FURNITURE'), 
('REPAIRS');

#create expence table
CREATE TABLE EXPENCES (

);
